---
- name: Testing andrewrothstein.subgit
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'subgit --version'
      ansible.builtin.command: sh -lc 'subgit --version'
      changed_when: false
      register: subgit_test_output
    - name: Output from 'subgit --version'
      ansible.builtin.debug:
        msg: '{{ subgit_test_output.stdout }}'
