---
- name: download
  become: yes
  become_user: root
  get_url: >
    url={{subgit_zip_url}}
    dest=/tmp/{{subgit_zip}}'
    mode=0644

- name: unachive
  become: yes
  become_user: root
  unarchive: >
    copy=no
    src=/tmp/{{subgit_zip}}
    dest={{subgit_home}}

- name: link subgit
  become: yes
  become_user: root
  file: >
    src={{subgit_home}}/{{subgit_name}}
    dest={{subgit_home}}/subgit
    state=link

- name: add subgit into the default path
  become: yes
  become_user: root
  with_items:
    - etc/profile.d/subgit.sh
  template: >
    src={{item}}.j2
    dest=/{{item}}
