---
- name: download
  become: yes
  become_user: root
  get_url:
    url: '{{subgit_zip_url}}'
    dest: /tmp/{{subgit_zip}}
    mode: 0644
    timeout: '{{subgit_timeout_seconds}}'
    checksum: '{{subgit_checksum}}'

- name: unachive
  become: yes
  become_user: root
  unarchive:
    remote_src: no
    src: /tmp/{{subgit_zip}}
    dest: '{{subgit_parent_install_dir}}'

- name: link subgit
  become: yes
  become_user: root
  file:
    src: '{{subgit_install_dir}}'
    dest: '{{subgit_parent_install_dir}}/subgit'
    state: link

- name: add subgit into the default path
  become: yes
  become_user: root
  with_items:
    - d: /etc/profile.d
      f: subgit.sh
      m: '0644'
  template:
    src: '{{item.f}}.j2'
    dest: '{{item.d}}/{{item.f}}'
    mode: '{{item.m}}'
