---
- include_role:
    name: andrewrothstein.unarchivedeps
- include_role:
    name: andrewrothstein.temurin
  vars:
    openjdk_app: jre
- name: check for install in {{ subgit_install_dir }}
  become: true
  stat:
    path: '{{ subgit_install_dir }}'
  changed_when: false
  register: subgit_binary
- when: not subgit_binary.stat.exists
  block:
    - name: downloading {{ subgit_zip_url }}
      become: true
      become_user: root
      get_url:
        url: '{{ subgit_zip_url }}'
        dest: '{{ subgit_tmp_zip }}'
        mode: 0644
        timeout: '{{ subgit_timeout_seconds }}'
        checksum: '{{ subgit_zip_checksum }}'
    - name: unarchiving {{ subgit_tmp_zip }}
      become: true
      become_user: root
      unarchive:
        remote_src: true
        src: '{{ subgit_tmp_zip }}'
        dest: '{{ subgit_parent_install_dir }}'
        creates: '{{ subgit_install_dir }}'
  always:
    - name: rm {{ subgit_tmp_zip }}
      become: true
      become_user: root
      file:
        path: '{{ subgit_tmp_zip }}'
        state: absent
- name: linking {{ subgit_link_dir }} to {{ subgit_install_dir }}
  become: true
  become_user: root
  file:
    src: '{{ subgit_install_dir }}'
    dest: '{{ subgit_link_dir }}'
    state: link

- name: add subgit into the default path
  become: true
  become_user: root
  with_items:
    - d: /etc/profile.d
      f: subgit.sh
  template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m|default("0644") }}'
