---
- name: Installing andrewrothstein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Installing andrewrothstein.temurin
  ansible.builtin.include_role:
    name: andrewrothstein.temurin
  vars:
    temurin_app: jre
- name: Check for install in {{ subgit_install_dir }}
  become: true
  ansible.builtin.stat:
    path: '{{ subgit_install_dir }}'
  changed_when: false
  register: subgit_binary
- name: Downloading subgit
  when: not subgit_binary.stat.exists
  block:
    - name: Downloading {{ subgit_zip_url }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ subgit_zip_url }}'
        dest: '{{ subgit_tmp_zip }}'
        mode: '644'
        timeout: '{{ subgit_timeout_seconds }}'
        checksum: '{{ subgit_zip_checksum }}'
    - name: Unarchiving {{ subgit_tmp_zip }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ subgit_tmp_zip }}'
        dest: '{{ subgit_parent_install_dir }}'
        creates: '{{ subgit_install_dir }}'
  always:
    - name: Rm -f {{ subgit_tmp_zip }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ subgit_tmp_zip }}'
        state: absent
- name: Linking {{ subgit_link_dir }} to {{ subgit_install_dir }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ subgit_install_dir }}'
    dest: '{{ subgit_link_dir }}'
    state: link

- name: Add subgit into the default path
  become: true
  become_user: root
  with_items:
    - d: /etc/profile.d
      f: subgit.sh
  ansible.builtin.template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m | default("644") }}'
